// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: services.proto

package mackerelcachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\x0fmackerelcachepb\x1a\x0emessages.proto2\xd1\x10\n" +
	"\x14MackerelCacheService\x12B\n" +
	"\x03Get\x12\x1b.mackerelcachepb.GetRequest\x1a\x1c.mackerelcachepb.GetResponse\"\x00\x12N\n" +
	"\aGetMany\x12\x1f.mackerelcachepb.GetManyRequest\x1a .mackerelcachepb.GetManyResponse\"\x00\x12H\n" +
	"\x05Touch\x12\x1d.mackerelcachepb.TouchRequest\x1a\x1e.mackerelcachepb.TouchResponse\"\x00\x12T\n" +
	"\tTouchMany\x12!.mackerelcachepb.TouchManyRequest\x1a\".mackerelcachepb.TouchManyResponse\"\x00\x12B\n" +
	"\x03Ttl\x12\x1b.mackerelcachepb.TtlRequest\x1a\x1c.mackerelcachepb.TtlResponse\"\x00\x12N\n" +
	"\aTtlMany\x12\x1f.mackerelcachepb.TtlManyRequest\x1a .mackerelcachepb.TtlManyResponse\"\x00\x12B\n" +
	"\x03Put\x12\x1b.mackerelcachepb.PutRequest\x1a\x1c.mackerelcachepb.PutResponse\"\x00\x12N\n" +
	"\aPutMany\x12\x1f.mackerelcachepb.PutManyRequest\x1a .mackerelcachepb.PutManyResponse\"\x00\x12c\n" +
	"\x0ePutIfNotExists\x12&.mackerelcachepb.PutIfNotExistsRequest\x1a'.mackerelcachepb.PutIfNotExistsResponse\"\x00\x12o\n" +
	"\x12PutIfNotExistsMany\x12*.mackerelcachepb.PutIfNotExistsManyRequest\x1a+.mackerelcachepb.PutIfNotExistsManyResponse\"\x00\x12Z\n" +
	"\vPutIfExists\x12#.mackerelcachepb.PutIfExistsRequest\x1a$.mackerelcachepb.PutIfExistsResponse\"\x00\x12f\n" +
	"\x0fPutIfExistsMany\x12'.mackerelcachepb.PutIfExistsManyRequest\x1a(.mackerelcachepb.PutIfExistsManyResponse\"\x00\x12K\n" +
	"\x06Delete\x12\x1e.mackerelcachepb.DeleteRequest\x1a\x1f.mackerelcachepb.DeleteResponse\"\x00\x12W\n" +
	"\n" +
	"DeleteMany\x12\".mackerelcachepb.DeleteManyRequest\x1a#.mackerelcachepb.DeleteManyResponse\"\x00\x12c\n" +
	"\x0eFlushPartition\x12&.mackerelcachepb.FlushPartitionRequest\x1a'.mackerelcachepb.FlushPartitionResponse\"\x00\x12f\n" +
	"\x0fDeletePartition\x12'.mackerelcachepb.DeletePartitionRequest\x1a(.mackerelcachepb.DeletePartitionResponse\"\x00\x12]\n" +
	"\fPutPartition\x12$.mackerelcachepb.PutPartitionRequest\x1a%.mackerelcachepb.PutPartitionResponse\"\x00\x12Q\n" +
	"\bFlushAll\x12 .mackerelcachepb.FlushAllRequest\x1a!.mackerelcachepb.FlushAllResponse\"\x00\x12e\n" +
	"\x0eScanPartitions\x12&.mackerelcachepb.ScanPartitionsRequest\x1a'.mackerelcachepb.ScanPartitionsResponse\"\x000\x01\x12S\n" +
	"\bScanKeys\x12 .mackerelcachepb.ScanKeysRequest\x1a!.mackerelcachepb.ScanKeysResponse\"\x000\x01\x12T\n" +
	"\tIncrement\x12!.mackerelcachepb.IncrementRequest\x1a\".mackerelcachepb.IncrementResponse\"\x00\x12Z\n" +
	"\vIncrementBy\x12#.mackerelcachepb.IncrementByRequest\x1a$.mackerelcachepb.IncrementByResponse\"\x00\x12T\n" +
	"\tDecrement\x12!.mackerelcachepb.DecrementRequest\x1a\".mackerelcachepb.DecrementResponse\"\x00\x12Z\n" +
	"\vDecrementBy\x12#.mackerelcachepb.DecrementByRequest\x1a$.mackerelcachepb.DecrementByResponse\"\x002\\\n" +
	"\fWatchService\x12L\n" +
	"\x05Watch\x12\x1d.mackerelcachepb.WatchRequest\x1a\x1e.mackerelcachepb.WatchResponse\"\x00(\x010\x012\xb1\x03\n" +
	"\x12MaintenanceService\x12K\n" +
	"\bGetStats\x12 .mackerelcachepb.GetStatsRequest\x1a\x1b.mackerelcachepb.CacheStats\"\x00\x12Q\n" +
	"\aGetConf\x12\x1f.mackerelcachepb.GetConfRequest\x1a#.mackerelcachepb.CacheConfiguration\"\x00\x12Q\n" +
	"\bInvokeGC\x12 .mackerelcachepb.InvokeGCRequest\x1a!.mackerelcachepb.InvokeGCResponse\"\x00\x12E\n" +
	"\x04Ping\x12\x1c.mackerelcachepb.PingRequest\x1a\x1d.mackerelcachepb.PongResponse\"\x00\x12a\n" +
	"\x11GetPartitionStats\x12).mackerelcachepb.GetPartitionStatsRequest\x1a\x1f.mackerelcachepb.PartitionStats\"\x00B?Z=github.com/chadjefferies/go-mackerelcache/api/mackerelcachepbb\x06proto3"

var file_services_proto_goTypes = []any{
	(*GetRequest)(nil),                 // 0: mackerelcachepb.GetRequest
	(*GetManyRequest)(nil),             // 1: mackerelcachepb.GetManyRequest
	(*TouchRequest)(nil),               // 2: mackerelcachepb.TouchRequest
	(*TouchManyRequest)(nil),           // 3: mackerelcachepb.TouchManyRequest
	(*TtlRequest)(nil),                 // 4: mackerelcachepb.TtlRequest
	(*TtlManyRequest)(nil),             // 5: mackerelcachepb.TtlManyRequest
	(*PutRequest)(nil),                 // 6: mackerelcachepb.PutRequest
	(*PutManyRequest)(nil),             // 7: mackerelcachepb.PutManyRequest
	(*PutIfNotExistsRequest)(nil),      // 8: mackerelcachepb.PutIfNotExistsRequest
	(*PutIfNotExistsManyRequest)(nil),  // 9: mackerelcachepb.PutIfNotExistsManyRequest
	(*PutIfExistsRequest)(nil),         // 10: mackerelcachepb.PutIfExistsRequest
	(*PutIfExistsManyRequest)(nil),     // 11: mackerelcachepb.PutIfExistsManyRequest
	(*DeleteRequest)(nil),              // 12: mackerelcachepb.DeleteRequest
	(*DeleteManyRequest)(nil),          // 13: mackerelcachepb.DeleteManyRequest
	(*FlushPartitionRequest)(nil),      // 14: mackerelcachepb.FlushPartitionRequest
	(*DeletePartitionRequest)(nil),     // 15: mackerelcachepb.DeletePartitionRequest
	(*PutPartitionRequest)(nil),        // 16: mackerelcachepb.PutPartitionRequest
	(*FlushAllRequest)(nil),            // 17: mackerelcachepb.FlushAllRequest
	(*ScanPartitionsRequest)(nil),      // 18: mackerelcachepb.ScanPartitionsRequest
	(*ScanKeysRequest)(nil),            // 19: mackerelcachepb.ScanKeysRequest
	(*IncrementRequest)(nil),           // 20: mackerelcachepb.IncrementRequest
	(*IncrementByRequest)(nil),         // 21: mackerelcachepb.IncrementByRequest
	(*DecrementRequest)(nil),           // 22: mackerelcachepb.DecrementRequest
	(*DecrementByRequest)(nil),         // 23: mackerelcachepb.DecrementByRequest
	(*WatchRequest)(nil),               // 24: mackerelcachepb.WatchRequest
	(*GetStatsRequest)(nil),            // 25: mackerelcachepb.GetStatsRequest
	(*GetConfRequest)(nil),             // 26: mackerelcachepb.GetConfRequest
	(*InvokeGCRequest)(nil),            // 27: mackerelcachepb.InvokeGCRequest
	(*PingRequest)(nil),                // 28: mackerelcachepb.PingRequest
	(*GetPartitionStatsRequest)(nil),   // 29: mackerelcachepb.GetPartitionStatsRequest
	(*GetResponse)(nil),                // 30: mackerelcachepb.GetResponse
	(*GetManyResponse)(nil),            // 31: mackerelcachepb.GetManyResponse
	(*TouchResponse)(nil),              // 32: mackerelcachepb.TouchResponse
	(*TouchManyResponse)(nil),          // 33: mackerelcachepb.TouchManyResponse
	(*TtlResponse)(nil),                // 34: mackerelcachepb.TtlResponse
	(*TtlManyResponse)(nil),            // 35: mackerelcachepb.TtlManyResponse
	(*PutResponse)(nil),                // 36: mackerelcachepb.PutResponse
	(*PutManyResponse)(nil),            // 37: mackerelcachepb.PutManyResponse
	(*PutIfNotExistsResponse)(nil),     // 38: mackerelcachepb.PutIfNotExistsResponse
	(*PutIfNotExistsManyResponse)(nil), // 39: mackerelcachepb.PutIfNotExistsManyResponse
	(*PutIfExistsResponse)(nil),        // 40: mackerelcachepb.PutIfExistsResponse
	(*PutIfExistsManyResponse)(nil),    // 41: mackerelcachepb.PutIfExistsManyResponse
	(*DeleteResponse)(nil),             // 42: mackerelcachepb.DeleteResponse
	(*DeleteManyResponse)(nil),         // 43: mackerelcachepb.DeleteManyResponse
	(*FlushPartitionResponse)(nil),     // 44: mackerelcachepb.FlushPartitionResponse
	(*DeletePartitionResponse)(nil),    // 45: mackerelcachepb.DeletePartitionResponse
	(*PutPartitionResponse)(nil),       // 46: mackerelcachepb.PutPartitionResponse
	(*FlushAllResponse)(nil),           // 47: mackerelcachepb.FlushAllResponse
	(*ScanPartitionsResponse)(nil),     // 48: mackerelcachepb.ScanPartitionsResponse
	(*ScanKeysResponse)(nil),           // 49: mackerelcachepb.ScanKeysResponse
	(*IncrementResponse)(nil),          // 50: mackerelcachepb.IncrementResponse
	(*IncrementByResponse)(nil),        // 51: mackerelcachepb.IncrementByResponse
	(*DecrementResponse)(nil),          // 52: mackerelcachepb.DecrementResponse
	(*DecrementByResponse)(nil),        // 53: mackerelcachepb.DecrementByResponse
	(*WatchResponse)(nil),              // 54: mackerelcachepb.WatchResponse
	(*CacheStats)(nil),                 // 55: mackerelcachepb.CacheStats
	(*CacheConfiguration)(nil),         // 56: mackerelcachepb.CacheConfiguration
	(*InvokeGCResponse)(nil),           // 57: mackerelcachepb.InvokeGCResponse
	(*PongResponse)(nil),               // 58: mackerelcachepb.PongResponse
	(*PartitionStats)(nil),             // 59: mackerelcachepb.PartitionStats
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: mackerelcachepb.MackerelCacheService.Get:input_type -> mackerelcachepb.GetRequest
	1,  // 1: mackerelcachepb.MackerelCacheService.GetMany:input_type -> mackerelcachepb.GetManyRequest
	2,  // 2: mackerelcachepb.MackerelCacheService.Touch:input_type -> mackerelcachepb.TouchRequest
	3,  // 3: mackerelcachepb.MackerelCacheService.TouchMany:input_type -> mackerelcachepb.TouchManyRequest
	4,  // 4: mackerelcachepb.MackerelCacheService.Ttl:input_type -> mackerelcachepb.TtlRequest
	5,  // 5: mackerelcachepb.MackerelCacheService.TtlMany:input_type -> mackerelcachepb.TtlManyRequest
	6,  // 6: mackerelcachepb.MackerelCacheService.Put:input_type -> mackerelcachepb.PutRequest
	7,  // 7: mackerelcachepb.MackerelCacheService.PutMany:input_type -> mackerelcachepb.PutManyRequest
	8,  // 8: mackerelcachepb.MackerelCacheService.PutIfNotExists:input_type -> mackerelcachepb.PutIfNotExistsRequest
	9,  // 9: mackerelcachepb.MackerelCacheService.PutIfNotExistsMany:input_type -> mackerelcachepb.PutIfNotExistsManyRequest
	10, // 10: mackerelcachepb.MackerelCacheService.PutIfExists:input_type -> mackerelcachepb.PutIfExistsRequest
	11, // 11: mackerelcachepb.MackerelCacheService.PutIfExistsMany:input_type -> mackerelcachepb.PutIfExistsManyRequest
	12, // 12: mackerelcachepb.MackerelCacheService.Delete:input_type -> mackerelcachepb.DeleteRequest
	13, // 13: mackerelcachepb.MackerelCacheService.DeleteMany:input_type -> mackerelcachepb.DeleteManyRequest
	14, // 14: mackerelcachepb.MackerelCacheService.FlushPartition:input_type -> mackerelcachepb.FlushPartitionRequest
	15, // 15: mackerelcachepb.MackerelCacheService.DeletePartition:input_type -> mackerelcachepb.DeletePartitionRequest
	16, // 16: mackerelcachepb.MackerelCacheService.PutPartition:input_type -> mackerelcachepb.PutPartitionRequest
	17, // 17: mackerelcachepb.MackerelCacheService.FlushAll:input_type -> mackerelcachepb.FlushAllRequest
	18, // 18: mackerelcachepb.MackerelCacheService.ScanPartitions:input_type -> mackerelcachepb.ScanPartitionsRequest
	19, // 19: mackerelcachepb.MackerelCacheService.ScanKeys:input_type -> mackerelcachepb.ScanKeysRequest
	20, // 20: mackerelcachepb.MackerelCacheService.Increment:input_type -> mackerelcachepb.IncrementRequest
	21, // 21: mackerelcachepb.MackerelCacheService.IncrementBy:input_type -> mackerelcachepb.IncrementByRequest
	22, // 22: mackerelcachepb.MackerelCacheService.Decrement:input_type -> mackerelcachepb.DecrementRequest
	23, // 23: mackerelcachepb.MackerelCacheService.DecrementBy:input_type -> mackerelcachepb.DecrementByRequest
	24, // 24: mackerelcachepb.WatchService.Watch:input_type -> mackerelcachepb.WatchRequest
	25, // 25: mackerelcachepb.MaintenanceService.GetStats:input_type -> mackerelcachepb.GetStatsRequest
	26, // 26: mackerelcachepb.MaintenanceService.GetConf:input_type -> mackerelcachepb.GetConfRequest
	27, // 27: mackerelcachepb.MaintenanceService.InvokeGC:input_type -> mackerelcachepb.InvokeGCRequest
	28, // 28: mackerelcachepb.MaintenanceService.Ping:input_type -> mackerelcachepb.PingRequest
	29, // 29: mackerelcachepb.MaintenanceService.GetPartitionStats:input_type -> mackerelcachepb.GetPartitionStatsRequest
	30, // 30: mackerelcachepb.MackerelCacheService.Get:output_type -> mackerelcachepb.GetResponse
	31, // 31: mackerelcachepb.MackerelCacheService.GetMany:output_type -> mackerelcachepb.GetManyResponse
	32, // 32: mackerelcachepb.MackerelCacheService.Touch:output_type -> mackerelcachepb.TouchResponse
	33, // 33: mackerelcachepb.MackerelCacheService.TouchMany:output_type -> mackerelcachepb.TouchManyResponse
	34, // 34: mackerelcachepb.MackerelCacheService.Ttl:output_type -> mackerelcachepb.TtlResponse
	35, // 35: mackerelcachepb.MackerelCacheService.TtlMany:output_type -> mackerelcachepb.TtlManyResponse
	36, // 36: mackerelcachepb.MackerelCacheService.Put:output_type -> mackerelcachepb.PutResponse
	37, // 37: mackerelcachepb.MackerelCacheService.PutMany:output_type -> mackerelcachepb.PutManyResponse
	38, // 38: mackerelcachepb.MackerelCacheService.PutIfNotExists:output_type -> mackerelcachepb.PutIfNotExistsResponse
	39, // 39: mackerelcachepb.MackerelCacheService.PutIfNotExistsMany:output_type -> mackerelcachepb.PutIfNotExistsManyResponse
	40, // 40: mackerelcachepb.MackerelCacheService.PutIfExists:output_type -> mackerelcachepb.PutIfExistsResponse
	41, // 41: mackerelcachepb.MackerelCacheService.PutIfExistsMany:output_type -> mackerelcachepb.PutIfExistsManyResponse
	42, // 42: mackerelcachepb.MackerelCacheService.Delete:output_type -> mackerelcachepb.DeleteResponse
	43, // 43: mackerelcachepb.MackerelCacheService.DeleteMany:output_type -> mackerelcachepb.DeleteManyResponse
	44, // 44: mackerelcachepb.MackerelCacheService.FlushPartition:output_type -> mackerelcachepb.FlushPartitionResponse
	45, // 45: mackerelcachepb.MackerelCacheService.DeletePartition:output_type -> mackerelcachepb.DeletePartitionResponse
	46, // 46: mackerelcachepb.MackerelCacheService.PutPartition:output_type -> mackerelcachepb.PutPartitionResponse
	47, // 47: mackerelcachepb.MackerelCacheService.FlushAll:output_type -> mackerelcachepb.FlushAllResponse
	48, // 48: mackerelcachepb.MackerelCacheService.ScanPartitions:output_type -> mackerelcachepb.ScanPartitionsResponse
	49, // 49: mackerelcachepb.MackerelCacheService.ScanKeys:output_type -> mackerelcachepb.ScanKeysResponse
	50, // 50: mackerelcachepb.MackerelCacheService.Increment:output_type -> mackerelcachepb.IncrementResponse
	51, // 51: mackerelcachepb.MackerelCacheService.IncrementBy:output_type -> mackerelcachepb.IncrementByResponse
	52, // 52: mackerelcachepb.MackerelCacheService.Decrement:output_type -> mackerelcachepb.DecrementResponse
	53, // 53: mackerelcachepb.MackerelCacheService.DecrementBy:output_type -> mackerelcachepb.DecrementByResponse
	54, // 54: mackerelcachepb.WatchService.Watch:output_type -> mackerelcachepb.WatchResponse
	55, // 55: mackerelcachepb.MaintenanceService.GetStats:output_type -> mackerelcachepb.CacheStats
	56, // 56: mackerelcachepb.MaintenanceService.GetConf:output_type -> mackerelcachepb.CacheConfiguration
	57, // 57: mackerelcachepb.MaintenanceService.InvokeGC:output_type -> mackerelcachepb.InvokeGCResponse
	58, // 58: mackerelcachepb.MaintenanceService.Ping:output_type -> mackerelcachepb.PongResponse
	59, // 59: mackerelcachepb.MaintenanceService.GetPartitionStats:output_type -> mackerelcachepb.PartitionStats
	30, // [30:60] is the sub-list for method output_type
	0,  // [0:30] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
