// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.1
// source: services.proto

package mackerelcachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MackerelCacheService_Get_FullMethodName                = "/mackerelcachepb.MackerelCacheService/Get"
	MackerelCacheService_GetMany_FullMethodName            = "/mackerelcachepb.MackerelCacheService/GetMany"
	MackerelCacheService_Touch_FullMethodName              = "/mackerelcachepb.MackerelCacheService/Touch"
	MackerelCacheService_TouchMany_FullMethodName          = "/mackerelcachepb.MackerelCacheService/TouchMany"
	MackerelCacheService_Ttl_FullMethodName                = "/mackerelcachepb.MackerelCacheService/Ttl"
	MackerelCacheService_TtlMany_FullMethodName            = "/mackerelcachepb.MackerelCacheService/TtlMany"
	MackerelCacheService_Put_FullMethodName                = "/mackerelcachepb.MackerelCacheService/Put"
	MackerelCacheService_PutMany_FullMethodName            = "/mackerelcachepb.MackerelCacheService/PutMany"
	MackerelCacheService_PutIfNotExists_FullMethodName     = "/mackerelcachepb.MackerelCacheService/PutIfNotExists"
	MackerelCacheService_PutIfNotExistsMany_FullMethodName = "/mackerelcachepb.MackerelCacheService/PutIfNotExistsMany"
	MackerelCacheService_PutIfExists_FullMethodName        = "/mackerelcachepb.MackerelCacheService/PutIfExists"
	MackerelCacheService_PutIfExistsMany_FullMethodName    = "/mackerelcachepb.MackerelCacheService/PutIfExistsMany"
	MackerelCacheService_Delete_FullMethodName             = "/mackerelcachepb.MackerelCacheService/Delete"
	MackerelCacheService_DeleteMany_FullMethodName         = "/mackerelcachepb.MackerelCacheService/DeleteMany"
	MackerelCacheService_FlushPartition_FullMethodName     = "/mackerelcachepb.MackerelCacheService/FlushPartition"
	MackerelCacheService_DeletePartition_FullMethodName    = "/mackerelcachepb.MackerelCacheService/DeletePartition"
	MackerelCacheService_PutPartition_FullMethodName       = "/mackerelcachepb.MackerelCacheService/PutPartition"
	MackerelCacheService_FlushAll_FullMethodName           = "/mackerelcachepb.MackerelCacheService/FlushAll"
	MackerelCacheService_ScanPartitions_FullMethodName     = "/mackerelcachepb.MackerelCacheService/ScanPartitions"
	MackerelCacheService_ScanKeys_FullMethodName           = "/mackerelcachepb.MackerelCacheService/ScanKeys"
	MackerelCacheService_Increment_FullMethodName          = "/mackerelcachepb.MackerelCacheService/Increment"
	MackerelCacheService_IncrementBy_FullMethodName        = "/mackerelcachepb.MackerelCacheService/IncrementBy"
	MackerelCacheService_Decrement_FullMethodName          = "/mackerelcachepb.MackerelCacheService/Decrement"
	MackerelCacheService_DecrementBy_FullMethodName        = "/mackerelcachepb.MackerelCacheService/DecrementBy"
)

// MackerelCacheServiceClient is the client API for MackerelCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for the Mackerel cache API.
// A distributed in-memory key-value store.
type MackerelCacheServiceClient interface {
	// Gets the value at the specified key.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Gets the values at the specified keys.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	GetMany(ctx context.Context, in *GetManyRequest, opts ...grpc.CallOption) (*GetManyResponse, error)
	// Updates the last access time of a key.
	// Only supported for partitions with sliding expiration set.
	Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*TouchResponse, error)
	// Updates the last access time of the specified keys.
	// Only supported for partitions with sliding expiration set.
	TouchMany(ctx context.Context, in *TouchManyRequest, opts ...grpc.CallOption) (*TouchManyResponse, error)
	// Returns the remaining time to live (ms) of a key.
	// Returns -1 if the key has no expiration and -2 if the key does not exist.
	Ttl(ctx context.Context, in *TtlRequest, opts ...grpc.CallOption) (*TtlResponse, error)
	// Returns the remaining time to live (ms) of the specified keys.
	// Returns -1 if the key has no expiration and -2 if the key does not exist.
	TtlMany(ctx context.Context, in *TtlManyRequest, opts ...grpc.CallOption) (*TtlManyResponse, error)
	// Sets a key-value in the cache. If it already exists,
	// it's updated, if it doesn't exist, a new entry is created.
	// As a side effect of calling this function:
	// 1. The value's last access time is updated.
	// 2. The global count stats are updated.
	// 3. Any watchers of affected keys are notified
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Sets multiple key-value pairs in the cache. If they already exist,
	// they're updated, if they don't exist, new entries are created.
	// As a side effect of calling this function:
	// 1. The values last access time is updated.
	// 2. The global count stats are updated.
	// 3. Any watchers of affected keys are notified
	PutMany(ctx context.Context, in *PutManyRequest, opts ...grpc.CallOption) (*PutManyResponse, error)
	// Sets a key-value in the cache only if it doesn't already exist.
	// As a side effect of calling this function:
	// 1. The value's last access time is updated.
	// 2. The global count stats are updated.
	// 3. If the key already exists but is expired, it is updated.
	// 4. Any watchers of affected keys are notified
	PutIfNotExists(ctx context.Context, in *PutIfNotExistsRequest, opts ...grpc.CallOption) (*PutIfNotExistsResponse, error)
	// Sets multiple key-value pairs in the cache only if they don't already exist.
	// As a side effect of calling this function:
	// 1. The values last access time is updated.
	// 2. The global count stats are updated.
	// 3. If a key already exists but is expired, it is updated.
	// 4. Any watchers of affected keys are notified
	PutIfNotExistsMany(ctx context.Context, in *PutIfNotExistsManyRequest, opts ...grpc.CallOption) (*PutIfNotExistsManyResponse, error)
	// Sets a key-value in the cache only if exists already.
	// As a side effect of calling this function:
	// 1. The value's last access time is updated.
	// 2. The global count stats are updated.
	// 3. If the key already exists but is expired, it is not updated.
	// 4. Any watchers of affected keys are notified
	PutIfExists(ctx context.Context, in *PutIfExistsRequest, opts ...grpc.CallOption) (*PutIfExistsResponse, error)
	// Sets multiple key-value pairs in the cache only if they exist already.
	// As a side effect of calling this function:
	// 1. The values last access time is updated.
	// 2. The global count stats are updated.
	// 3. If a key already exists but is expired, it is not updated.
	// 4. Any watchers of affected keys are notified
	PutIfExistsMany(ctx context.Context, in *PutIfExistsManyRequest, opts ...grpc.CallOption) (*PutIfExistsManyResponse, error)
	// Deletes a value by key.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Deletes multiple values by key.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	DeleteMany(ctx context.Context, in *DeleteManyRequest, opts ...grpc.CallOption) (*DeleteManyResponse, error)
	// Flushes the entire partition and resets the count stats. The partition metadata remains in the cache.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	FlushPartition(ctx context.Context, in *FlushPartitionRequest, opts ...grpc.CallOption) (*FlushPartitionResponse, error)
	// Flushes the entire partition, resets the count stats, and removes the partition metadata from the cache.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	DeletePartition(ctx context.Context, in *DeletePartitionRequest, opts ...grpc.CallOption) (*DeletePartitionResponse, error)
	// Sets a partition in the cache. If it already exists,
	// it's updated, if it doesn't exist, a new partition is created.
	// Only partitions created through this method have the option
	// to have their metadata persisted.
	PutPartition(ctx context.Context, in *PutPartitionRequest, opts ...grpc.CallOption) (*PutPartitionResponse, error)
	// Removes all data from the cache across all partitions.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	FlushAll(ctx context.Context, in *FlushAllRequest, opts ...grpc.CallOption) (*FlushAllResponse, error)
	// Iterates all partitions and returns matching results based on a glob-style pattern.
	// Only offers limited guarantees about the returned elements since the collection
	// that we iterate may change during the iteration process.
	ScanPartitions(ctx context.Context, in *ScanPartitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanPartitionsResponse], error)
	// Iterates all keys in a given partition and returns matching results based on a glob-style pattern.
	// Only offers limited guarantees about the returned elements since the collection
	// that we iterate may change during the iteration process.
	// As a side effect of calling this function, any matching keys:
	// 1. A value gets expired if it reached it's TTL.
	ScanKeys(ctx context.Context, in *ScanKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanKeysResponse], error)
	// Increments a number stored at a key. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*IncrementResponse, error)
	// Increments a number stored at a key by the requested value. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	IncrementBy(ctx context.Context, in *IncrementByRequest, opts ...grpc.CallOption) (*IncrementByResponse, error)
	// Decrements a number stored at a key. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	Decrement(ctx context.Context, in *DecrementRequest, opts ...grpc.CallOption) (*DecrementResponse, error)
	// Decrements a number stored at a key by the requested value. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	DecrementBy(ctx context.Context, in *DecrementByRequest, opts ...grpc.CallOption) (*DecrementByResponse, error)
}

type mackerelCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMackerelCacheServiceClient(cc grpc.ClientConnInterface) MackerelCacheServiceClient {
	return &mackerelCacheServiceClient{cc}
}

func (c *mackerelCacheServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) GetMany(ctx context.Context, in *GetManyRequest, opts ...grpc.CallOption) (*GetManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManyResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_GetMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*TouchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TouchResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_Touch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) TouchMany(ctx context.Context, in *TouchManyRequest, opts ...grpc.CallOption) (*TouchManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TouchManyResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_TouchMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) Ttl(ctx context.Context, in *TtlRequest, opts ...grpc.CallOption) (*TtlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TtlResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_Ttl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) TtlMany(ctx context.Context, in *TtlManyRequest, opts ...grpc.CallOption) (*TtlManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TtlManyResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_TtlMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) PutMany(ctx context.Context, in *PutManyRequest, opts ...grpc.CallOption) (*PutManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutManyResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_PutMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) PutIfNotExists(ctx context.Context, in *PutIfNotExistsRequest, opts ...grpc.CallOption) (*PutIfNotExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutIfNotExistsResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_PutIfNotExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) PutIfNotExistsMany(ctx context.Context, in *PutIfNotExistsManyRequest, opts ...grpc.CallOption) (*PutIfNotExistsManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutIfNotExistsManyResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_PutIfNotExistsMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) PutIfExists(ctx context.Context, in *PutIfExistsRequest, opts ...grpc.CallOption) (*PutIfExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutIfExistsResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_PutIfExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) PutIfExistsMany(ctx context.Context, in *PutIfExistsManyRequest, opts ...grpc.CallOption) (*PutIfExistsManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutIfExistsManyResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_PutIfExistsMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) DeleteMany(ctx context.Context, in *DeleteManyRequest, opts ...grpc.CallOption) (*DeleteManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManyResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_DeleteMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) FlushPartition(ctx context.Context, in *FlushPartitionRequest, opts ...grpc.CallOption) (*FlushPartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushPartitionResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_FlushPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) DeletePartition(ctx context.Context, in *DeletePartitionRequest, opts ...grpc.CallOption) (*DeletePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePartitionResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_DeletePartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) PutPartition(ctx context.Context, in *PutPartitionRequest, opts ...grpc.CallOption) (*PutPartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPartitionResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_PutPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) FlushAll(ctx context.Context, in *FlushAllRequest, opts ...grpc.CallOption) (*FlushAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushAllResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_FlushAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) ScanPartitions(ctx context.Context, in *ScanPartitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanPartitionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MackerelCacheService_ServiceDesc.Streams[0], MackerelCacheService_ScanPartitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanPartitionsRequest, ScanPartitionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MackerelCacheService_ScanPartitionsClient = grpc.ServerStreamingClient[ScanPartitionsResponse]

func (c *mackerelCacheServiceClient) ScanKeys(ctx context.Context, in *ScanKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanKeysResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MackerelCacheService_ServiceDesc.Streams[1], MackerelCacheService_ScanKeys_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanKeysRequest, ScanKeysResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MackerelCacheService_ScanKeysClient = grpc.ServerStreamingClient[ScanKeysResponse]

func (c *mackerelCacheServiceClient) Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*IncrementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_Increment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) IncrementBy(ctx context.Context, in *IncrementByRequest, opts ...grpc.CallOption) (*IncrementByResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementByResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_IncrementBy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) Decrement(ctx context.Context, in *DecrementRequest, opts ...grpc.CallOption) (*DecrementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrementResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_Decrement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mackerelCacheServiceClient) DecrementBy(ctx context.Context, in *DecrementByRequest, opts ...grpc.CallOption) (*DecrementByResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrementByResponse)
	err := c.cc.Invoke(ctx, MackerelCacheService_DecrementBy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MackerelCacheServiceServer is the server API for MackerelCacheService service.
// All implementations must embed UnimplementedMackerelCacheServiceServer
// for forward compatibility.
//
// Service definition for the Mackerel cache API.
// A distributed in-memory key-value store.
type MackerelCacheServiceServer interface {
	// Gets the value at the specified key.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Gets the values at the specified keys.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	GetMany(context.Context, *GetManyRequest) (*GetManyResponse, error)
	// Updates the last access time of a key.
	// Only supported for partitions with sliding expiration set.
	Touch(context.Context, *TouchRequest) (*TouchResponse, error)
	// Updates the last access time of the specified keys.
	// Only supported for partitions with sliding expiration set.
	TouchMany(context.Context, *TouchManyRequest) (*TouchManyResponse, error)
	// Returns the remaining time to live (ms) of a key.
	// Returns -1 if the key has no expiration and -2 if the key does not exist.
	Ttl(context.Context, *TtlRequest) (*TtlResponse, error)
	// Returns the remaining time to live (ms) of the specified keys.
	// Returns -1 if the key has no expiration and -2 if the key does not exist.
	TtlMany(context.Context, *TtlManyRequest) (*TtlManyResponse, error)
	// Sets a key-value in the cache. If it already exists,
	// it's updated, if it doesn't exist, a new entry is created.
	// As a side effect of calling this function:
	// 1. The value's last access time is updated.
	// 2. The global count stats are updated.
	// 3. Any watchers of affected keys are notified
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Sets multiple key-value pairs in the cache. If they already exist,
	// they're updated, if they don't exist, new entries are created.
	// As a side effect of calling this function:
	// 1. The values last access time is updated.
	// 2. The global count stats are updated.
	// 3. Any watchers of affected keys are notified
	PutMany(context.Context, *PutManyRequest) (*PutManyResponse, error)
	// Sets a key-value in the cache only if it doesn't already exist.
	// As a side effect of calling this function:
	// 1. The value's last access time is updated.
	// 2. The global count stats are updated.
	// 3. If the key already exists but is expired, it is updated.
	// 4. Any watchers of affected keys are notified
	PutIfNotExists(context.Context, *PutIfNotExistsRequest) (*PutIfNotExistsResponse, error)
	// Sets multiple key-value pairs in the cache only if they don't already exist.
	// As a side effect of calling this function:
	// 1. The values last access time is updated.
	// 2. The global count stats are updated.
	// 3. If a key already exists but is expired, it is updated.
	// 4. Any watchers of affected keys are notified
	PutIfNotExistsMany(context.Context, *PutIfNotExistsManyRequest) (*PutIfNotExistsManyResponse, error)
	// Sets a key-value in the cache only if exists already.
	// As a side effect of calling this function:
	// 1. The value's last access time is updated.
	// 2. The global count stats are updated.
	// 3. If the key already exists but is expired, it is not updated.
	// 4. Any watchers of affected keys are notified
	PutIfExists(context.Context, *PutIfExistsRequest) (*PutIfExistsResponse, error)
	// Sets multiple key-value pairs in the cache only if they exist already.
	// As a side effect of calling this function:
	// 1. The values last access time is updated.
	// 2. The global count stats are updated.
	// 3. If a key already exists but is expired, it is not updated.
	// 4. Any watchers of affected keys are notified
	PutIfExistsMany(context.Context, *PutIfExistsManyRequest) (*PutIfExistsManyResponse, error)
	// Deletes a value by key.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Deletes multiple values by key.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	DeleteMany(context.Context, *DeleteManyRequest) (*DeleteManyResponse, error)
	// Flushes the entire partition and resets the count stats. The partition metadata remains in the cache.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	FlushPartition(context.Context, *FlushPartitionRequest) (*FlushPartitionResponse, error)
	// Flushes the entire partition, resets the count stats, and removes the partition metadata from the cache.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	DeletePartition(context.Context, *DeletePartitionRequest) (*DeletePartitionResponse, error)
	// Sets a partition in the cache. If it already exists,
	// it's updated, if it doesn't exist, a new partition is created.
	// Only partitions created through this method have the option
	// to have their metadata persisted.
	PutPartition(context.Context, *PutPartitionRequest) (*PutPartitionResponse, error)
	// Removes all data from the cache across all partitions.
	// As a side effect of calling this function:
	// 1. The global count stats are updated.
	// 2. Any watchers of affected keys are notified
	FlushAll(context.Context, *FlushAllRequest) (*FlushAllResponse, error)
	// Iterates all partitions and returns matching results based on a glob-style pattern.
	// Only offers limited guarantees about the returned elements since the collection
	// that we iterate may change during the iteration process.
	ScanPartitions(*ScanPartitionsRequest, grpc.ServerStreamingServer[ScanPartitionsResponse]) error
	// Iterates all keys in a given partition and returns matching results based on a glob-style pattern.
	// Only offers limited guarantees about the returned elements since the collection
	// that we iterate may change during the iteration process.
	// As a side effect of calling this function, any matching keys:
	// 1. A value gets expired if it reached it's TTL.
	ScanKeys(*ScanKeysRequest, grpc.ServerStreamingServer[ScanKeysResponse]) error
	// Increments a number stored at a key. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	Increment(context.Context, *IncrementRequest) (*IncrementResponse, error)
	// Increments a number stored at a key by the requested value. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	IncrementBy(context.Context, *IncrementByRequest) (*IncrementByResponse, error)
	// Decrements a number stored at a key. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	Decrement(context.Context, *DecrementRequest) (*DecrementResponse, error)
	// Decrements a number stored at a key by the requested value. If it doesn't exist,
	// it is assumed to be zero before running the request.
	// As a side effect of calling this function:
	// 1. A value gets expired if it reached it's TTL.
	// 2. The value's last access time is updated.
	// 3. The global hit/miss/count stats are updated.
	// 4. Any watchers of affected keys are notified
	DecrementBy(context.Context, *DecrementByRequest) (*DecrementByResponse, error)
	mustEmbedUnimplementedMackerelCacheServiceServer()
}

// UnimplementedMackerelCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMackerelCacheServiceServer struct{}

func (UnimplementedMackerelCacheServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMackerelCacheServiceServer) GetMany(context.Context, *GetManyRequest) (*GetManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMany not implemented")
}
func (UnimplementedMackerelCacheServiceServer) Touch(context.Context, *TouchRequest) (*TouchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Touch not implemented")
}
func (UnimplementedMackerelCacheServiceServer) TouchMany(context.Context, *TouchManyRequest) (*TouchManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TouchMany not implemented")
}
func (UnimplementedMackerelCacheServiceServer) Ttl(context.Context, *TtlRequest) (*TtlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ttl not implemented")
}
func (UnimplementedMackerelCacheServiceServer) TtlMany(context.Context, *TtlManyRequest) (*TtlManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TtlMany not implemented")
}
func (UnimplementedMackerelCacheServiceServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedMackerelCacheServiceServer) PutMany(context.Context, *PutManyRequest) (*PutManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutMany not implemented")
}
func (UnimplementedMackerelCacheServiceServer) PutIfNotExists(context.Context, *PutIfNotExistsRequest) (*PutIfNotExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutIfNotExists not implemented")
}
func (UnimplementedMackerelCacheServiceServer) PutIfNotExistsMany(context.Context, *PutIfNotExistsManyRequest) (*PutIfNotExistsManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutIfNotExistsMany not implemented")
}
func (UnimplementedMackerelCacheServiceServer) PutIfExists(context.Context, *PutIfExistsRequest) (*PutIfExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutIfExists not implemented")
}
func (UnimplementedMackerelCacheServiceServer) PutIfExistsMany(context.Context, *PutIfExistsManyRequest) (*PutIfExistsManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutIfExistsMany not implemented")
}
func (UnimplementedMackerelCacheServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMackerelCacheServiceServer) DeleteMany(context.Context, *DeleteManyRequest) (*DeleteManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMany not implemented")
}
func (UnimplementedMackerelCacheServiceServer) FlushPartition(context.Context, *FlushPartitionRequest) (*FlushPartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushPartition not implemented")
}
func (UnimplementedMackerelCacheServiceServer) DeletePartition(context.Context, *DeletePartitionRequest) (*DeletePartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePartition not implemented")
}
func (UnimplementedMackerelCacheServiceServer) PutPartition(context.Context, *PutPartitionRequest) (*PutPartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutPartition not implemented")
}
func (UnimplementedMackerelCacheServiceServer) FlushAll(context.Context, *FlushAllRequest) (*FlushAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushAll not implemented")
}
func (UnimplementedMackerelCacheServiceServer) ScanPartitions(*ScanPartitionsRequest, grpc.ServerStreamingServer[ScanPartitionsResponse]) error {
	return status.Error(codes.Unimplemented, "method ScanPartitions not implemented")
}
func (UnimplementedMackerelCacheServiceServer) ScanKeys(*ScanKeysRequest, grpc.ServerStreamingServer[ScanKeysResponse]) error {
	return status.Error(codes.Unimplemented, "method ScanKeys not implemented")
}
func (UnimplementedMackerelCacheServiceServer) Increment(context.Context, *IncrementRequest) (*IncrementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedMackerelCacheServiceServer) IncrementBy(context.Context, *IncrementByRequest) (*IncrementByResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementBy not implemented")
}
func (UnimplementedMackerelCacheServiceServer) Decrement(context.Context, *DecrementRequest) (*DecrementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decrement not implemented")
}
func (UnimplementedMackerelCacheServiceServer) DecrementBy(context.Context, *DecrementByRequest) (*DecrementByResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecrementBy not implemented")
}
func (UnimplementedMackerelCacheServiceServer) mustEmbedUnimplementedMackerelCacheServiceServer() {}
func (UnimplementedMackerelCacheServiceServer) testEmbeddedByValue()                              {}

// UnsafeMackerelCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MackerelCacheServiceServer will
// result in compilation errors.
type UnsafeMackerelCacheServiceServer interface {
	mustEmbedUnimplementedMackerelCacheServiceServer()
}

func RegisterMackerelCacheServiceServer(s grpc.ServiceRegistrar, srv MackerelCacheServiceServer) {
	// If the following call panics, it indicates UnimplementedMackerelCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MackerelCacheService_ServiceDesc, srv)
}

func _MackerelCacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_GetMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).GetMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_GetMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).GetMany(ctx, req.(*GetManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_Touch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).Touch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_Touch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).Touch(ctx, req.(*TouchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_TouchMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).TouchMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_TouchMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).TouchMany(ctx, req.(*TouchManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_Ttl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TtlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).Ttl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_Ttl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).Ttl(ctx, req.(*TtlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_TtlMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TtlManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).TtlMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_TtlMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).TtlMany(ctx, req.(*TtlManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_PutMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).PutMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_PutMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).PutMany(ctx, req.(*PutManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_PutIfNotExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIfNotExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).PutIfNotExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_PutIfNotExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).PutIfNotExists(ctx, req.(*PutIfNotExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_PutIfNotExistsMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIfNotExistsManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).PutIfNotExistsMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_PutIfNotExistsMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).PutIfNotExistsMany(ctx, req.(*PutIfNotExistsManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_PutIfExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIfExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).PutIfExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_PutIfExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).PutIfExists(ctx, req.(*PutIfExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_PutIfExistsMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIfExistsManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).PutIfExistsMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_PutIfExistsMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).PutIfExistsMany(ctx, req.(*PutIfExistsManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_DeleteMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).DeleteMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_DeleteMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).DeleteMany(ctx, req.(*DeleteManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_FlushPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).FlushPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_FlushPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).FlushPartition(ctx, req.(*FlushPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_DeletePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).DeletePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_DeletePartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).DeletePartition(ctx, req.(*DeletePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_PutPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).PutPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_PutPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).PutPartition(ctx, req.(*PutPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_FlushAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).FlushAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_FlushAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).FlushAll(ctx, req.(*FlushAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_ScanPartitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanPartitionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MackerelCacheServiceServer).ScanPartitions(m, &grpc.GenericServerStream[ScanPartitionsRequest, ScanPartitionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MackerelCacheService_ScanPartitionsServer = grpc.ServerStreamingServer[ScanPartitionsResponse]

func _MackerelCacheService_ScanKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MackerelCacheServiceServer).ScanKeys(m, &grpc.GenericServerStream[ScanKeysRequest, ScanKeysResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MackerelCacheService_ScanKeysServer = grpc.ServerStreamingServer[ScanKeysResponse]

func _MackerelCacheService_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_Increment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).Increment(ctx, req.(*IncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_IncrementBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).IncrementBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_IncrementBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).IncrementBy(ctx, req.(*IncrementByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_Decrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).Decrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_Decrement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).Decrement(ctx, req.(*DecrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MackerelCacheService_DecrementBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MackerelCacheServiceServer).DecrementBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MackerelCacheService_DecrementBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MackerelCacheServiceServer).DecrementBy(ctx, req.(*DecrementByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MackerelCacheService_ServiceDesc is the grpc.ServiceDesc for MackerelCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MackerelCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mackerelcachepb.MackerelCacheService",
	HandlerType: (*MackerelCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MackerelCacheService_Get_Handler,
		},
		{
			MethodName: "GetMany",
			Handler:    _MackerelCacheService_GetMany_Handler,
		},
		{
			MethodName: "Touch",
			Handler:    _MackerelCacheService_Touch_Handler,
		},
		{
			MethodName: "TouchMany",
			Handler:    _MackerelCacheService_TouchMany_Handler,
		},
		{
			MethodName: "Ttl",
			Handler:    _MackerelCacheService_Ttl_Handler,
		},
		{
			MethodName: "TtlMany",
			Handler:    _MackerelCacheService_TtlMany_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _MackerelCacheService_Put_Handler,
		},
		{
			MethodName: "PutMany",
			Handler:    _MackerelCacheService_PutMany_Handler,
		},
		{
			MethodName: "PutIfNotExists",
			Handler:    _MackerelCacheService_PutIfNotExists_Handler,
		},
		{
			MethodName: "PutIfNotExistsMany",
			Handler:    _MackerelCacheService_PutIfNotExistsMany_Handler,
		},
		{
			MethodName: "PutIfExists",
			Handler:    _MackerelCacheService_PutIfExists_Handler,
		},
		{
			MethodName: "PutIfExistsMany",
			Handler:    _MackerelCacheService_PutIfExistsMany_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MackerelCacheService_Delete_Handler,
		},
		{
			MethodName: "DeleteMany",
			Handler:    _MackerelCacheService_DeleteMany_Handler,
		},
		{
			MethodName: "FlushPartition",
			Handler:    _MackerelCacheService_FlushPartition_Handler,
		},
		{
			MethodName: "DeletePartition",
			Handler:    _MackerelCacheService_DeletePartition_Handler,
		},
		{
			MethodName: "PutPartition",
			Handler:    _MackerelCacheService_PutPartition_Handler,
		},
		{
			MethodName: "FlushAll",
			Handler:    _MackerelCacheService_FlushAll_Handler,
		},
		{
			MethodName: "Increment",
			Handler:    _MackerelCacheService_Increment_Handler,
		},
		{
			MethodName: "IncrementBy",
			Handler:    _MackerelCacheService_IncrementBy_Handler,
		},
		{
			MethodName: "Decrement",
			Handler:    _MackerelCacheService_Decrement_Handler,
		},
		{
			MethodName: "DecrementBy",
			Handler:    _MackerelCacheService_DecrementBy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScanPartitions",
			Handler:       _MackerelCacheService_ScanPartitions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ScanKeys",
			Handler:       _MackerelCacheService_ScanKeys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services.proto",
}

const (
	WatchService_Watch_FullMethodName = "/mackerelcachepb.WatchService/Watch"
)

// WatchServiceClient is the client API for WatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchServiceClient interface {
	// Watches for changes to keys. Both input and output are streams;
	// the input stream is for periodically sending heartbeats and the output
	// stream sends key change events.
	Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, WatchResponse], error)
}

type watchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchServiceClient(cc grpc.ClientConnInterface) WatchServiceClient {
	return &watchServiceClient{cc}
}

func (c *watchServiceClient) Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WatchService_ServiceDesc.Streams[0], WatchService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WatchService_WatchClient = grpc.BidiStreamingClient[WatchRequest, WatchResponse]

// WatchServiceServer is the server API for WatchService service.
// All implementations must embed UnimplementedWatchServiceServer
// for forward compatibility.
type WatchServiceServer interface {
	// Watches for changes to keys. Both input and output are streams;
	// the input stream is for periodically sending heartbeats and the output
	// stream sends key change events.
	Watch(grpc.BidiStreamingServer[WatchRequest, WatchResponse]) error
	mustEmbedUnimplementedWatchServiceServer()
}

// UnimplementedWatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchServiceServer struct{}

func (UnimplementedWatchServiceServer) Watch(grpc.BidiStreamingServer[WatchRequest, WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedWatchServiceServer) mustEmbedUnimplementedWatchServiceServer() {}
func (UnimplementedWatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeWatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchServiceServer will
// result in compilation errors.
type UnsafeWatchServiceServer interface {
	mustEmbedUnimplementedWatchServiceServer()
}

func RegisterWatchServiceServer(s grpc.ServiceRegistrar, srv WatchServiceServer) {
	// If the following call panics, it indicates UnimplementedWatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchService_ServiceDesc, srv)
}

func _WatchService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WatchServiceServer).Watch(&grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WatchService_WatchServer = grpc.BidiStreamingServer[WatchRequest, WatchResponse]

// WatchService_ServiceDesc is the grpc.ServiceDesc for WatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mackerelcachepb.WatchService",
	HandlerType: (*WatchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _WatchService_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services.proto",
}

const (
	MaintenanceService_GetStats_FullMethodName          = "/mackerelcachepb.MaintenanceService/GetStats"
	MaintenanceService_GetConf_FullMethodName           = "/mackerelcachepb.MaintenanceService/GetConf"
	MaintenanceService_InvokeGC_FullMethodName          = "/mackerelcachepb.MaintenanceService/InvokeGC"
	MaintenanceService_Ping_FullMethodName              = "/mackerelcachepb.MaintenanceService/Ping"
	MaintenanceService_GetPartitionStats_FullMethodName = "/mackerelcachepb.MaintenanceService/GetPartitionStats"
)

// MaintenanceServiceClient is the client API for MaintenanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaintenanceServiceClient interface {
	// Returns the global stats such as hits, misses, etc.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*CacheStats, error)
	// Returns the configuration settings for the node
	GetConf(ctx context.Context, in *GetConfRequest, opts ...grpc.CallOption) (*CacheConfiguration, error)
	// Forces an immediate collection of all generations and compacts the LOH. This is not recommended.
	InvokeGC(ctx context.Context, in *InvokeGCRequest, opts ...grpc.CallOption) (*InvokeGCResponse, error)
	// Ping the node to check availability
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
	// Returns partition level stats for a single partition.
	GetPartitionStats(ctx context.Context, in *GetPartitionStatsRequest, opts ...grpc.CallOption) (*PartitionStats, error)
}

type maintenanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaintenanceServiceClient(cc grpc.ClientConnInterface) MaintenanceServiceClient {
	return &maintenanceServiceClient{cc}
}

func (c *maintenanceServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*CacheStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheStats)
	err := c.cc.Invoke(ctx, MaintenanceService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceServiceClient) GetConf(ctx context.Context, in *GetConfRequest, opts ...grpc.CallOption) (*CacheConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheConfiguration)
	err := c.cc.Invoke(ctx, MaintenanceService_GetConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceServiceClient) InvokeGC(ctx context.Context, in *InvokeGCRequest, opts ...grpc.CallOption) (*InvokeGCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeGCResponse)
	err := c.cc.Invoke(ctx, MaintenanceService_InvokeGC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, MaintenanceService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceServiceClient) GetPartitionStats(ctx context.Context, in *GetPartitionStatsRequest, opts ...grpc.CallOption) (*PartitionStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionStats)
	err := c.cc.Invoke(ctx, MaintenanceService_GetPartitionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaintenanceServiceServer is the server API for MaintenanceService service.
// All implementations must embed UnimplementedMaintenanceServiceServer
// for forward compatibility.
type MaintenanceServiceServer interface {
	// Returns the global stats such as hits, misses, etc.
	GetStats(context.Context, *GetStatsRequest) (*CacheStats, error)
	// Returns the configuration settings for the node
	GetConf(context.Context, *GetConfRequest) (*CacheConfiguration, error)
	// Forces an immediate collection of all generations and compacts the LOH. This is not recommended.
	InvokeGC(context.Context, *InvokeGCRequest) (*InvokeGCResponse, error)
	// Ping the node to check availability
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	// Returns partition level stats for a single partition.
	GetPartitionStats(context.Context, *GetPartitionStatsRequest) (*PartitionStats, error)
	mustEmbedUnimplementedMaintenanceServiceServer()
}

// UnimplementedMaintenanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaintenanceServiceServer struct{}

func (UnimplementedMaintenanceServiceServer) GetStats(context.Context, *GetStatsRequest) (*CacheStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMaintenanceServiceServer) GetConf(context.Context, *GetConfRequest) (*CacheConfiguration, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConf not implemented")
}
func (UnimplementedMaintenanceServiceServer) InvokeGC(context.Context, *InvokeGCRequest) (*InvokeGCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeGC not implemented")
}
func (UnimplementedMaintenanceServiceServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMaintenanceServiceServer) GetPartitionStats(context.Context, *GetPartitionStatsRequest) (*PartitionStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartitionStats not implemented")
}
func (UnimplementedMaintenanceServiceServer) mustEmbedUnimplementedMaintenanceServiceServer() {}
func (UnimplementedMaintenanceServiceServer) testEmbeddedByValue()                            {}

// UnsafeMaintenanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaintenanceServiceServer will
// result in compilation errors.
type UnsafeMaintenanceServiceServer interface {
	mustEmbedUnimplementedMaintenanceServiceServer()
}

func RegisterMaintenanceServiceServer(s grpc.ServiceRegistrar, srv MaintenanceServiceServer) {
	// If the following call panics, it indicates UnimplementedMaintenanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaintenanceService_ServiceDesc, srv)
}

func _MaintenanceService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintenanceService_GetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServiceServer).GetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceService_GetConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServiceServer).GetConf(ctx, req.(*GetConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintenanceService_InvokeGC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeGCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServiceServer).InvokeGC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceService_InvokeGC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServiceServer).InvokeGC(ctx, req.(*InvokeGCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintenanceService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintenanceService_GetPartitionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceServiceServer).GetPartitionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceService_GetPartitionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceServiceServer).GetPartitionStats(ctx, req.(*GetPartitionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MaintenanceService_ServiceDesc is the grpc.ServiceDesc for MaintenanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaintenanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mackerelcachepb.MaintenanceService",
	HandlerType: (*MaintenanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _MaintenanceService_GetStats_Handler,
		},
		{
			MethodName: "GetConf",
			Handler:    _MaintenanceService_GetConf_Handler,
		},
		{
			MethodName: "InvokeGC",
			Handler:    _MaintenanceService_InvokeGC_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MaintenanceService_Ping_Handler,
		},
		{
			MethodName: "GetPartitionStats",
			Handler:    _MaintenanceService_GetPartitionStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
